package com.telegram.bot.model;

public enum BotState {
    START,
    WEATHER,
    FORECAST,
    SETTINGS,
    LANGUAGE,
    LOCATIONS,
    ADD_LOCATION,
    ADD_LOCATION_FOR_NEW_USER,
    DELETE_LOCATION,
    LOCATION_BY_COORDINATE,
    LOCATION_BY_CHAT,
    BACK,
    SELECT_LOCATION
}
